#!/usr/bin/env python3
"""
HKO DAEMON v5.1 - Desktop Standalone with HKO Standard UI/UX
Status: STABLE | Architecture: Headless Service (FastAPI)
Changes: Desktop-safe paths, embedded UI, enriched logging, dry-run clarity
"""

import os
import sys
import shutil
import json
import hashlib
import asyncio
import sqlite3
import uvicorn
import zipfile
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional, Union
from concurrent.futures import ProcessPoolExecutor
from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

# ... [CONFIGURATION CONSTANTS - Same as v5.0] ...
APP_NAME = "HKO DAEMON"
VERSION = "v5.1"
DESKTOP_PATH = Path(os.path.expanduser("~/Desktop"))
HKO_ROOT = DESKTOP_PATH / "HKO_METAVERSE"
LOGS_ROOT = HKO_ROOT / "LOGS"
SCHEMA_HASH = "init"  # Placeholder for schema versioning

# =============================================================================
# SETUP HELPERS
# =============================================================================

def ensure_environment() -> None:
    """Guarantee the desktop-safe directories exist for a truly standalone experience."""
    HKO_ROOT.mkdir(parents=True, exist_ok=True)
    LOGS_ROOT.mkdir(parents=True, exist_ok=True)
    desktop_marker = HKO_ROOT / "README.txt"
    if not desktop_marker.exists():
        desktop_marker.write_text(
            "HKO Metaverse home. Generated by HKO DAEMON v5.1 for desktop operations.",
            encoding="utf-8",
        )


def log_event(message: str, level: str = "info") -> Dict[str, str]:
    """Append a structured log entry and persist it to the desktop log file."""
    timestamp = datetime.now().isoformat()
    entry = {"time": timestamp, "msg": message, "type": level}
    LOGS_ROOT.mkdir(parents=True, exist_ok=True)
    logfile = LOGS_ROOT / "daemon.log"
    with logfile.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(entry) + "\n")
    return entry


def read_recent_logs(limit: int = 30) -> List[Dict[str, str]]:
    logfile = LOGS_ROOT / "daemon.log"
    if not logfile.exists():
        return []
    with logfile.open("r", encoding="utf-8") as handle:
        lines = handle.readlines()[-limit:]
    return [json.loads(line) for line in lines if line.strip()]

# =============================================================================
# UTILS
# =============================================================================

def is_file_locked(filepath):
    """Checks if a file is locked by another process."""
    if not os.path.exists(filepath): return False
    try:
        # Try to rename it to itself (atomic check)
        os.rename(filepath, filepath)
        return False
    except OSError:
        return True

# =============================================================================
# DATA MODELS
# =============================================================================

class MoveRequest(BaseModel):
    src_path: str
    dest_folder: str
    dry_run: bool = True

# =============================================================================
# CORE LOGIC
# =============================================================================

class OrganizeEngine:
    def __init__(self):
        ensure_environment()

    def scan_desktop(self):
        candidates = []
        for item in DESKTOP_PATH.iterdir():
            if item.is_file() and item.name != "desktop.ini":
                candidates.append(
                    {
                        "path": str(item),
                        "name": item.name,
                        "suggestion": "Unsorted",
                        "size_kb": round(item.stat().st_size / 1024, 2),
                    }
                )
        return candidates

    def execute_move(self, src_path: str, dest_folder: str, dry_run: bool) -> Dict:
        src = Path(src_path)
        if not src.exists():
            return {"success": False, "message": "Source missing", "action": "none"}
        
        target_dir = DESKTOP_PATH / dest_folder
        dest = target_dir / src.name
        
        if dest.exists():
            dest = target_dir / f"{src.stem}_{int(datetime.now().timestamp())}{src.suffix}"
            
        if dry_run:
            # IMPROVED SIMULATION
            if is_file_locked(src):
                return {
                    "success": False,
                    "message": f"[DRY-RUN] File is LOCKED by another app: {src.name}",
                    "action": "lock_error",
                }
                
            return {
                "success": True,
                "message": f"[DRY-RUN] Verified & Ready: {src.name} -> {dest_folder}",
                "action": "simulate",
                "new_path": str(dest)
            }
        else:
            # EXECUTION
            try:
                target_dir.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dest))
                log_event(f"Moved {src.name} to {dest_folder}")
                return {
                    "success": True,
                    "message": f"[LIVE] Moved {src.name} to {dest_folder}",
                    "action": "move",
                    "new_path": str(dest)
                }
            except Exception as e:
                return {"success": False, "message": str(e), "action": "error"}


# =============================================================================
# UI TEMPLATE (HKO Standard UI/UX)
# =============================================================================

HKO_UI_HTML_TEMPLATE = r"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{APP_NAME} {VERSION}</title>
  <style>
    :root {
      --bg: #11161b;
      --panel: #1c242c;
      --card: #1f2b33;
      --accent: #2ab3c0;
      --accent-strong: #1f8a94;
      --border: rgba(255, 255, 255, 0.08);
      --text: #eaf2f7;
      --subtle: #8ea3b0;
      --warning: #e6893a;
      --success: #2cb88a;
      --error: #ff7b88;
      --shadow: 0 16px 48px rgba(0,0,0,0.35);
      font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    * { box-sizing: border-box; }
    body { margin: 0; background: radial-gradient(circle at 20% 20%, rgba(42,179,192,0.12), transparent 30%), var(--bg); color: var(--text); }
    h1 { font-size: 24px; letter-spacing: -0.02em; margin: 0; }
    p { margin: 0; color: var(--subtle); }
    a { color: var(--accent); }
    button {
      background: linear-gradient(135deg, var(--accent), var(--accent-strong));
      border: 1px solid var(--border);
      color: #0a1116;
      font-weight: 700;
      padding: 10px 14px;
      border-radius: 12px;
      cursor: pointer;
      transition: transform 160ms ease, box-shadow 160ms ease;
      box-shadow: var(--shadow);
    }
    button.secondary {
      background: transparent;
      color: var(--text);
      border: 1px solid var(--border);
      box-shadow: none;
    }
    button:hover { transform: translateY(-1px); }
    .app { max-width: 1100px; margin: 32px auto; padding: 0 20px 40px; display: grid; gap: 16px; }
    .card { background: var(--card); border: 1px solid var(--border); border-radius: 18px; padding: 16px; box-shadow: var(--shadow); }
    .grid-2 { display: grid; grid-template-columns: 1.2fr 1fr; gap: 16px; }
    .section-title { font-weight: 700; font-size: 14px; letter-spacing: 0.08em; color: var(--subtle); margin-bottom: 6px; text-transform: uppercase; }
    .row { display: flex; justify-content: space-between; align-items: center; gap: 12px; }
    .status-pill { padding: 6px 10px; border-radius: 999px; font-weight: 600; font-size: 12px; letter-spacing: 0.04em; display: inline-flex; align-items: center; gap: 8px; background: rgba(42,179,192,0.14); color: var(--accent); border: 1px solid rgba(42,179,192,0.3); }
    .pill-warning { background: rgba(230,137,58,0.12); color: var(--warning); border-color: rgba(230,137,58,0.3); }
    .pill-success { background: rgba(44,184,138,0.12); color: var(--success); border-color: rgba(44,184,138,0.3); }
    .pill-error { background: rgba(255,123,136,0.12); color: var(--error); border-color: rgba(255,123,136,0.3); }
    .table { width: 100%; border-spacing: 0; }
    .table th, .table td { text-align: left; padding: 10px 8px; border-bottom: 1px solid var(--border); font-size: 13px; }
    .table tbody tr:hover { background: rgba(255,255,255,0.02); }
    .log-feed { display: flex; flex-direction: column; gap: 10px; max-height: 300px; overflow: auto; padding-right: 4px; }
    .log-line { padding: 10px 12px; border-radius: 12px; border: 1px solid var(--border); background: rgba(255,255,255,0.02); }
    .muted { color: var(--subtle); font-size: 12px; }
    input { width: 100%; background: #0f151b; color: var(--text); border: 1px solid var(--border); border-radius: 12px; padding: 10px; font-size: 14px; }
    .stack { display: flex; flex-direction: column; gap: 10px; }
    .inline { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
    .badge { background: rgba(255,255,255,0.06); padding: 6px 8px; border-radius: 8px; border: 1px solid var(--border); font-size: 12px; color: var(--subtle); }
  </style>
</head>
<body>
  <div class="app">
    <div class="row">
      <div class="stack">
        <h1>{APP_NAME} <span style="color: var(--accent)">{VERSION}</span></h1>
        <p>Desktop-native daemon with safe dry-runs, inline confirmations, and the HKO standard card layout.</p>
      </div>
      <div class="status-pill" id="status-pill">Checking status…</div>
    </div>

    <div class="grid-2">
      <div class="card">
        <div class="section-title">Desktop Scan</div>
        <table class="table" id="candidate-table">
          <thead>
            <tr><th>File</th><th>Size (KB)</th><th>Action</th></tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>

      <div class="card stack">
        <div>
          <div class="section-title">Action Plan</div>
          <div class="stack">
            <label class="muted">Target folder (created on Desktop if missing)</label>
            <input id="destination" value="HKO_SORTED" />
            <div class="inline">
              <button id="simulate-btn">Dry Run</button>
              <button class="secondary" id="execute-btn">Execute Move</button>
            </div>
            <div class="inline">
              <span class="badge" id="selected-file">No file selected</span>
              <span class="badge" id="preview">Preview path pending</span>
            </div>
          </div>
        </div>
        <div class="stack">
          <div class="section-title">Activity Log</div>
          <div class="log-feed" id="log-feed"></div>
        </div>
      </div>
    </div>
  </div>

  <script>
    let selectedPath = null;

    const statusPill = document.getElementById('status-pill');
    const tableBody = document.querySelector('#candidate-table tbody');
    const logFeed = document.getElementById('log-feed');
    const selectedFile = document.getElementById('selected-file');
    const preview = document.getElementById('preview');

    function setPill(text, tone = 'info') {
      statusPill.textContent = text;
      statusPill.className = 'status-pill';
      if (tone === 'warn') statusPill.classList.add('pill-warning');
      if (tone === 'good') statusPill.classList.add('pill-success');
      if (tone === 'bad') statusPill.classList.add('pill-error');
    }

    async function refreshStatus() {
      const res = await fetch('/api/status');
      const data = await res.json();
      setPill(`${data.system} • ${data.status} • Desktop: ${data.desktop_ready ? 'OK' : 'Missing'}`, data.desktop_ready ? 'good' : 'warn');
    }

    function renderCandidates(items) {
      tableBody.innerHTML = '';
      if (!items.length) {
        tableBody.innerHTML = `<tr><td colspan='3' class='muted'>No loose files detected on Desktop.</td></tr>`;
        return;
      }
      items.forEach(item => {
        const row = document.createElement('tr');
        const select = () => {
          selectedPath = item.path;
          selectedFile.textContent = item.name;
          preview.textContent = `Will move into /Desktop/${document.getElementById('destination').value}`;
        };
        row.innerHTML = `<td>${item.name}</td><td>${item.size_kb}</td><td><button class='secondary'>Select</button></td>`;
        row.querySelector('button').onclick = select;
        row.onclick = select;
        tableBody.appendChild(row);
      });
    }

    async function refreshCandidates() {
      const res = await fetch('/api/organize/candidates');
      renderCandidates(await res.json());
    }

    function pushLog(entry) {
      const line = document.createElement('div');
      line.className = 'log-line';
      line.innerHTML = `<div class='muted'>${entry.time}</div><div>${entry.msg}</div>`;
      logFeed.prepend(line);
    }

    async function refreshLogs() {
      const res = await fetch('/api/logs/recent');
      const data = await res.json();
      logFeed.innerHTML = '';
      data.reverse().forEach(pushLog);
    }

    async function runJob(dryRun) {
      if (!selectedPath) { alert('Select a file first.'); return; }
      const dest = document.getElementById('destination').value || 'HKO_SORTED';
      const res = await fetch('/api/organize/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ src_path: selectedPath, dest_folder: dest, dry_run: dryRun })
      });
      const data = await res.json();
      pushLog({ time: new Date().toISOString(), msg: data.message, type: data.success ? 'info' : 'error' });
      if (!dryRun && data.success) { refreshCandidates(); }
    }

    document.getElementById('simulate-btn').onclick = () => runJob(true);
    document.getElementById('execute-btn').onclick = () => runJob(false);

    refreshStatus();
    refreshCandidates();
    refreshLogs();
    setInterval(refreshLogs, 4000);
  </script>
</body>
</html>
"""

HKO_UI_HTML = (
    HKO_UI_HTML_TEMPLATE.replace("{APP_NAME}", APP_NAME).replace("{VERSION}", VERSION)
)

# =============================================================================
# API LAYER
# =============================================================================

app = FastAPI(title=f"{APP_NAME} {VERSION}")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

organizer = OrganizeEngine()
log_event(f"{APP_NAME} {VERSION} booted and ready")


@app.get("/", response_class=HTMLResponse)
def serve_ui():
    return HKO_UI_HTML


@app.get("/api/status")
def status():
    ensure_environment()
    return {
        "system": APP_NAME,
        "version": VERSION,
        "status": "ONLINE",
        "schema_hash": SCHEMA_HASH,
        "desktop_ready": DESKTOP_PATH.exists(),
        "root": str(HKO_ROOT),
    }


@app.get("/api/organize/candidates")
def get_organize_candidates():
    return organizer.scan_desktop()


@app.post("/api/organize/execute")
def execute_organize_job(req: MoveRequest):
    result = organizer.execute_move(req.src_path, req.dest_folder, req.dry_run)
    if result.get("success"):
        tone = "info" if req.dry_run else "success"
        log_event(result["message"], level=tone)
    else:
        log_event(result.get("message", "Unknown error"), level="error")
    return result


@app.get("/api/logs/recent")
def get_recent_logs(limit: int = 20):  # Increased limit
    existing = read_recent_logs(limit)
    if not existing:
        return [log_event("System ready (v5.1 desktop standalone)")]
    return existing


if __name__ == "__main__":
    print(f"🛡️ {APP_NAME} {VERSION} INITIALIZED (DESKTOP MODE)")
    uvicorn.run(app, host="0.0.0.0", port=8000)